version: '3.9'
services:
  service_1:
    container_name: "AG-corp-service-1"
    build: user-side-service
    ports:
      - 8001:8001
    env_file:
      - user-side-service/.env

  service_2:
    container_name: "AG-corp-service-2"
    build: image-processing-service
    ports:
      - 8000:8000
