version: '3.9'
services:
  database:
    container_name: "AG-corp-DB"
    image: postgres:latest
    env_file:
      - user-side-service/db.env
    ports:
      - 5432:5432

  service_1:
    container_name: "AG-corp-service-1"
    image: test-image-2
    ports:
      - 8001:8001
    depends_on: 
      - database
    env_file:
      - user-side-service/.env
  
  service_2:
    container_name: "AG-corp-service-2"
    image: test-image-1
    ports:
      - 8000:8000


