version: "3.9"
services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - db.env
  app:
    image: test-image-1
    ports:
      - 8000:8000 

networks:
  host:
    